$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
metadata:
  name: ads-groups-ou-configuration
  version: 1.0.0
  description: Active Directory configuration for organizational units delegations
  Microsoft.DSC:
    requiredSecurityContext: current # this is the default and just used as an example indicating this config works for admins and non-admins

parameters:
  DomainRootPath:
    type: string
    defaultValue: "DC=contoso,DC=org"
resources:

# This configuration defines a security group for delegating permissions on the Production OU in Active Directory. The group is created with full control permissions on the OU, allowing members of the group to manage the OU and its contents effectively.


  - name: Active Directory Production OU Delegation Group Permissions
    type: ActiveDirectoryDsc/ADObjectPermissionEntry
    properties: 
      Ensure: Present
      Path: "[concat('OU=Production,', parameters('DomainRootPath'))]"
      IdentityReference: GDE-OU-Production-FullControl
      ActiveDirectoryRights: 
        - GenericAll
      AccessControlType: Allow
      ObjectType: 00000000-0000-0000-0000-000000000000
      ActiveDirectorySecurityInheritance: Descendents
      InheritedObjectType: 00000000-0000-0000-0000-000000000000

# This configuration defines a security group for delegating permissions on the Production-Accounts OU in Active Directory. The group is created with full control permissions on the OU, allowing members of the group to manage user accounts and other objects within the OU effectively.



  - name: Active Directory Production-Accounts OU Delegation Group Permissions Descendents
    type: ActiveDirectoryDsc/ADObjectPermissionEntry
    properties: 
      Ensure: Present
      Path: "[concat('OU=Accounts,OU=Production,', parameters('DomainRootPath'))]"
      IdentityReference: GDE-OU-Production-Accounts-RWD
      ActiveDirectoryRights: 
        - GenericAll
      AccessControlType: Allow
      ObjectType: 00000000-0000-0000-0000-000000000000
      ActiveDirectorySecurityInheritance: Descendents
      InheritedObjectType: User # User"


  - name: Active Directory Production-Accounts-Users OU Delegation Group Permissions Descendents
    type: ActiveDirectoryDsc/ADObjectPermissionEntry
    properties: 
      Ensure: Present
      Path: "[concat('OU=Users,OU=Accounts,OU=Production,', parameters('DomainRootPath'))]"
      IdentityReference: GDE-OU-Production-Accounts-Users-RWD
      ActiveDirectoryRights: 
        - GenericAll
      AccessControlType: Allow
      ObjectType: 00000000-0000-0000-0000-000000000000
      ActiveDirectorySecurityInheritance: Descendents
      InheritedObjectType: User # User

      ## User.NoSync

  - name: Active Directory Production-Accounts-Users.NoSync OU Delegation Group Permissions Descendents
    type: ActiveDirectoryDsc/ADObjectPermissionEntry
    properties: 
      Ensure: Present
      Path: "[concat('OU=Users.NoSync,OU=Accounts,OU=Production,', parameters('DomainRootPath'))]"
      IdentityReference: GDE-OU-Production-Accounts-Users.NoSync-RWD
      ActiveDirectoryRights: 
        - GenericAll
      AccessControlType: Allow
      ObjectType: 00000000-0000-0000-0000-000000000000
      ActiveDirectorySecurityInheritance: Descendents
      InheritedObjectType: User # User

     ## User.Service

  - name: Active Directory Production-Accounts-Users.Service OU Delegation Group Permissions Descendents
    type: ActiveDirectoryDsc/ADObjectPermissionEntry
    properties: 
      Ensure: Present
      Path: "[concat('OU=Users.Service,OU=Accounts,OU=Production,', parameters('DomainRootPath'))]"
      IdentityReference: GDE-OU-Production-Accounts-Users.Service-RWD
      ActiveDirectoryRights: 
        - GenericAll
      AccessControlType: Allow
      ObjectType: 00000000-0000-0000-0000-000000000000
      ActiveDirectorySecurityInheritance: Descendents
      InheritedObjectType: User # User


     ## User.Service.NoSync

  - name: Active Directory Production-Accounts-Users.Service.NoSync OU Delegation Group Permissions Descendents
    type: ActiveDirectoryDsc/ADObjectPermissionEntry
    properties: 
      Ensure: Present
      Path: "[concat('OU=Users.Service.NoSync,OU=Accounts,OU=Production,', parameters('DomainRootPath'))]"
      IdentityReference: GDE-OU-Production-Accounts-Users.Service.NoSync-RWD
      ActiveDirectoryRights: 
        - GenericAll
      AccessControlType: Allow
      ObjectType: 00000000-0000-0000-0000-000000000000
      ActiveDirectorySecurityInheritance: Descendents
      InheritedObjectType: User # User

     ## User.Service.Special

  - name: Active Directory Production-Accounts-Users.Special OU Delegation Group Permissions Descendents
    type: ActiveDirectoryDsc/ADObjectPermissionEntry
    properties: 
      Ensure: Present
      Path: "[concat('OU=Users.Special,OU=Accounts,OU=Production,', parameters('DomainRootPath'))]"
      IdentityReference: GDE-OU-Production-Accounts-Users.Special-RWD
      ActiveDirectoryRights: 
        - GenericAll
      AccessControlType: Allow
      ObjectType: 00000000-0000-0000-0000-000000000000
      ActiveDirectorySecurityInheritance: Descendents
      InheritedObjectType: User # User

     ## User.Service.Special.NoSync

  - name: Active Directory Production-Accounts-Users.Special.NoSync OU Delegation Group Permissions Descendents
    type: ActiveDirectoryDsc/ADObjectPermissionEntry
    properties: 
      Ensure: Present
      Path: "[concat('OU=Users.Special.NoSync,OU=Accounts,OU=Production,', parameters('DomainRootPath'))]"
      IdentityReference: GDE-OU-Production-Accounts-Users.Special.NoSync-RWD
      ActiveDirectoryRights: 
        - GenericAll
      AccessControlType: Allow
      ObjectType: 00000000-0000-0000-0000-000000000000
      ActiveDirectorySecurityInheritance: Descendents
      InheritedObjectType: User # User

      
# Computer objects in the Production-Devices OU are delegated to a security group with permissions to manage computer accounts and other objects within the OU effectively.

  - name: Active Directory Production-Devices OU Delegation Group Permissions
    type: ActiveDirectoryDsc/ADObjectPermissionEntry
    properties: 
      Ensure: Present
      Path: "[concat('OU=Devices,OU=Production,', parameters('DomainRootPath'))]"
      IdentityReference: GDE-OU-Production-Devices-RWD
      ActiveDirectoryRights: 
        - GenericAll
      AccessControlType: Allow
      ObjectType: 00000000-0000-0000-0000-000000000000
      ActiveDirectorySecurityInheritance: Descendents
      InheritedObjectType: Computer # Computer objects

 ## Computer objects in the Production-Devices-Computers OU are delegated to a security group with permissions to manage computer accounts and other objects within the OU effectively.

  - name: Active Directory Production-Devices-Computers OU Delegation Group Permissions
    type: ActiveDirectoryDsc/ADObjectPermissionEntry
    properties: 
      Ensure: Present
      Path: "[concat('OU=Computers,OU=Devices,OU=Production,', parameters('DomainRootPath'))]"
      IdentityReference: GDE-OU-Production-Devices-Computers-RWD
      ActiveDirectoryRights: 
        - GenericAll
      AccessControlType: Allow
      ObjectType: 00000000-0000-0000-0000-000000000000
      ActiveDirectorySecurityInheritance: Descendents
      InheritedObjectType: Computer # Computer objects

  ## Server objects in the Production-Devices-Servers OU are delegated to a security group with permissions to manage server accounts and other objects within the OU effectively.

  - name: Active Directory Production-Devices-Servers OU Delegation Group Permissions
    type: ActiveDirectoryDsc/ADObjectPermissionEntry
    properties: 
      Ensure: Present
      Path: "[concat('OU=Servers,OU=Devices,OU=Production,', parameters('DomainRootPath'))]"
      IdentityReference: GDE-OU-Production-Devices-Servers-RWD
      ActiveDirectoryRights: 
        - GenericAll
      AccessControlType: Allow
      ObjectType: 00000000-0000-0000-0000-000000000000
      ActiveDirectorySecurityInheritance: Descendents
      InheritedObjectType: Computer # Computer objects


  - name: Active Directory Production-Devices-Servers-Tier0 OU Delegation Group Permissions
    type: ActiveDirectoryDsc/ADObjectPermissionEntry
    properties: 
      Ensure: Present
      Path: "[concat('OU=Tier0,OU=Servers,OU=Devices,OU=Production,', parameters('DomainRootPath'))]"
      IdentityReference: GDE-OU-Production-Devices-Servers-Tier0-RWD
      ActiveDirectoryRights: 
        - GenericAll
      AccessControlType: Allow
      ObjectType: 00000000-0000-0000-0000-000000000000
      ActiveDirectorySecurityInheritance: Descendents
      InheritedObjectType: Computer # Computer objects

  - name: Active Directory Production-Devices-Servers-Tier1 OU Delegation Group Permissions
    type: ActiveDirectoryDsc/ADObjectPermissionEntry
    properties: 
      Ensure: Present
      Path: "[concat('OU=Tier1,OU=Servers,OU=Devices,OU=Production,', parameters('DomainRootPath'))]"
      IdentityReference: GDE-OU-Production-Devices-Servers-Tier1-RWD
      ActiveDirectoryRights: 
        - GenericAll
      AccessControlType: Allow
      ObjectType: 00000000-0000-0000-0000-000000000000
      ActiveDirectorySecurityInheritance: Descendents
      InheritedObjectType: Computer # Computer objects

  - name: Active Directory Production-Devices-Servers-Tier2 OU Delegation Group Permissions
    type: ActiveDirectoryDsc/ADObjectPermissionEntry
    properties: 
      Ensure: Present
      Path: "[concat('OU=Tier2,OU=Servers,OU=Devices,OU=Production,', parameters('DomainRootPath'))]"
      IdentityReference: GDE-OU-Production-Devices-Servers-Tier2-RWD
      ActiveDirectoryRights: 
        - GenericAll
      AccessControlType: Allow
      ObjectType: 00000000-0000-0000-0000-000000000000
      ActiveDirectorySecurityInheritance: Descendents
      InheritedObjectType: Computer # Computer objects


# Group created for delegating permissions on the Production-Shared OU in Active Directory. The group is created with full control permissions on the OU, allowing members of the group to manage shared resources and other objects within the OU effectively.
# no root delegation is created as Delegate OU is restricted for Domain Admins and Enterprise Admins groups only, so delegation groups are created for the child OUs only
# no security delegation is created on the root Production OU as it is restricted for Domain Admins and Enterprise Admins groups only, so delegation groups are created for the child OUs only

  - name: Active Directory Production-Groups-Distribution OU Delegation Group Permissions
    type: ActiveDirectoryDsc/ADObjectPermissionEntry
    properties: 
      Ensure: Present
      Path: "[concat('OU=Distribution,OU=Groups,OU=Production,', parameters('DomainRootPath'))]"
      IdentityReference: GDE-OU-Production-Groups-Distribution-RWD
      ActiveDirectoryRights: 
        - GenericAll
      AccessControlType: Allow
      ObjectType: 00000000-0000-0000-0000-000000000000
      ActiveDirectorySecurityInheritance: Descendents
      InheritedObjectType: Group # Group objects

  - name: Active Directory Production-Groups-Security-SecurityGeneral OU Delegation Group Permissions
    type: ActiveDirectoryDsc/ADObjectPermissionEntry
    properties: 
      Ensure: Present
      Path: "[concat('OU=SecurityGeneral,OU=Security,OU=Groups,OU=Production,', parameters('DomainRootPath'))]"
      IdentityReference: GDE-OU-Production-Groups-Security-SecurityGeneral-RWD
      ActiveDirectoryRights: 
        - GenericAll
      AccessControlType: Allow
      ObjectType: 00000000-0000-0000-0000-000000000000
      ActiveDirectorySecurityInheritance: Descendents
      InheritedObjectType: Group # Group objects




